name: CICD

on:
  push:
    branches: [main]
    
jobs:
  static-code-analysis:
    runs-on: [ubuntu-latest]
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/piyush8085/nodejs-app:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
  
  build:
    needs: static-code-analysis
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Building image tag
        run: |
         TAG="commit-${{ github.sha}}"

      - name: Viewing commit TAG
        run: echo "$TAG"

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }} 

      - name: Build docker image
        run: docker build -t piyush8085/nodejs-app:${{ github.sha }} .

      - name: Publish image to docker hub
        run: docker push piyush8085/nodejs-app:${{ github.sha}}


  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull piyush8085/nodejs-app:${{ github.sha }}

      - name: Delete old container
        run: sudo docker rm -f nodejs-app-container

      - name: Run docker container
        run: sudo docker run -d -p 5000:5000 --name nodejs-app-container piyush8085/nodejs-app:${{ github.sha }}