name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }} 
      - name: Build docker image
        run: docker build -t piyush8085/nodejs-app .
      - name: Publish image to docker hub
        run: docker push piyush8085/nodejs-app:latest